name: 'CI'

on:
  push:
    branches:
      - main
      - ipdk_v*
    paths-ignore:
      - 'build/networking/**'
      - 'build/networking_ebpf/**'
      - 'build/scripts/**'
  pull_request:
    branches:
      - main
      - ipdk_v*
    paths-ignore:
      - 'build/networking/**'
      - 'build/networking_ebpf/**'
      - 'build/scripts/**'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: makefile-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: shellcheck
      run: make -C build shellcheck

  build_containers:
    needs: shellcheck
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        # for OCI runner change to: runner: [ubuntu-latest, self-hosted]
        runner: [ubuntu-latest]
        os: [ubuntu2004, fedora33, ebpf-ubuntu2004]

    steps:
      - run: 'echo "No build required"'
