---
name: 'Storage Unit Tests Integration'

on:
  pull_request:
    branches:
      - main
      - ipdk_v*
    paths-ignore:
      - 'build/storage/**'
      - '.github/workflows/storage-ci.yml'
  push:
    branches:
      - main
      - ipdk_v*
    paths-ignore:
      - 'build/storage/**'
      - '.github/workflows/storage-ci.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: storage-ci-skip-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_storage_ut:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No Storage Unit Test Integration Required"'
  storage_build_containers:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No Storage Unit Test Integration Required"'
